version: "3"
services:
  nginx:
    image: velfrr/multi-container-web-app-nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    restart: always
  client:
    image: velfrr/multi-container-web-app-client
  api:
    image: velfrr/multi-container-web-app-api
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
  worker:
    image: velfrr/multi-container-web-app-worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
